string target_class
bool execute
---
uint16 OK=0
uint16 NO_TARGET=1
uint16 UNSTABLE_TARGET=2
uint16 SIZE_MISMATCH=3
uint16 AMBIGUOUS_TARGET=4
uint16 INVALID_DEPTH=5
uint16 TF_UNAVAILABLE=6
uint16 STALE_TARGET=7
uint16 CALIBRATION_UNVALIDATED=8
uint16 TABLE_UNCONFIGURED=9
uint16 PLANNING_FAILED=10
uint16 START_STATE_MISMATCH=11
uint16 WRIST_JUMP=12
uint16 CARTESIAN_INCOMPLETE=13
uint16 GRIPPER_FAULT=14
uint16 CONTACT_NOT_DETECTED=15
uint16 CANCELED=16
uint16 BUSY=17
uint16 EXECUTION_DISABLED=18
uint16 INTERNAL_ERROR=255
bool success
uint16 error_code
string message
geometry_msgs/PoseStamped object_pose
geometry_msgs/PoseStamped grasp_pose
geometry_msgs/Vector3 size
float64 contact_width
---
string stage
string detail
uint32 candidate_count
